### ISSUE TITLE
Crash with example on MINGW64 (MSYS2) and Python 3.8.1

### ISSUE THREAD

**Issue by eine** [Paebbels/pyAttributes#7]
The following MWE crashes:

```py
#!/usr/bin/env python3

import sys
from pyAttributes.ArgParseAttributes import ArgParseMixin, CommandAttribute, ArgumentAttribute

class MyProg(ArgParseMixin):
    def __init__(self):
        super().__init__()

    def Run(self):
        super().Run()

    # UserManagement commads
    @CommandAttribute('create-user', help="create-user help")
    @ArgumentAttribute(metavar='<Username>', dest="Users", type=str, nargs='+', help='todo help')
    def HandleCreateUser(self, args):
        print("HandleCreateUser: {0}".format(str(args.Users)))

    @CommandAttribute('remove-user',help="remove-user help")
    @ArgumentAttribute(metavar='<UserID>', dest="UserIDs", type=str, nargs='+', help='todo help')
    def HandleRemoveUser(self, args):
        print("HandleRemoveUser: {0}".format(str(args.UserIDs)))


if __name__ == "__main__":
    print (sys.version)
    prog = MyProg()
    prog.Run()
```

```sh
# ./cli.py 
3.8.1 (default, Dec 24 2019, 11:55:37)  [GCC 9.2.0 64 bit (AMD64)]
Traceback (most recent call last):
  File "./cli.py", line 28, in <module>
    prog.Run()
  File "./cli.py", line 11, in Run
    super().Run()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pyAttributes/ArgParseAttributes.py", line 192, in Run
    args.func(self, args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by Paebbels** [comment]
I finished my improvements to attributes in general. They do now adhere to the method-resolution-order (MRO). Thus, methods with atrributes from base-classes are now also found with e.g. `GetMethods`.

At next, I'll update the documentation concerning `ArgParse` related attributes and also add test cases for it.

**Comment by Paebbels** [comment]
@eine This should be solved. Please check again.

**Comment by eine** [comment]
Not exactly the MWE above, but the new example (https://pyattributes.readthedocs.io/en/latest/ArgParse.html#new-pyattributes-approach) works ok.
